package common

// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/Quantiex-Hub/x/common/querier
// ALIASGEN: github.com/Quantiex-Hub/x/common/types

import (
	"github.com/Quantiex-Hub/x/common/types"
)

var (
	// functions aliases
	NewEthereumAddress                = types.NewEthereumAddress
)

type (
	EthereumAddress          = types.EthereumAddress
	BinanceAddress            = types.BinanceAddress
)
